---
- name: Build maven war
  hosts: build
  become: yes

  tasks:
  - name: Ensure package is present
    apt:
     pkg:
       - maven
       - git
       - wget
     state: present
     update_cache: yes

  - name: Git clone boxfuse
    git:
     repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
     dest: /home/ubuntu/box
     clone: yes

  - name: Maven package
    shell:
      cmd: mvn package -f /home/ubuntu/box/pom.xml

  - name: Copy .war local machine
    fetch:
      src: /home/ubuntu/box/target/hello-1.0.war
      dest: /tmp/fetched

- name: Prod Tomcat
  hosts: prod
  become: yes

  tasks:
  - name: Ensure is present
    apt:
     name: tomcat9
     state: present
     update_cache: yes

  - name: Ensure index.html is present
    copy:
     src: /tmp/fetched/hello-1.0.war
     dest: /usr/local/tomcat/webapps/
