  version: "3"
  services:
    build:
      build: ./build
      volumes:
        - type: volume
          source: docker_share
          target: /usr/local/webapps

    prod:
      build: ./prod
      volumes:
         - type: volume
           source: docker_share
           target: /usr/local/build
      depends_on:
         - build
      ports:
         - "8080:8080"

  volumes:
     docker_share:

