  Version: '3'
  services:
    build:
      build: ./build
    volumes:
      - type: volume
        source: mymavenbox
        target: /maven_box/boxfuse-sample-java-war-hello/webapps/

    tomcat:
      build: ./prod
    volumes:
      - type: volume
        source: mymavenbox
        target: /maven_box/boxfuse-sample-java-war-hello/build
    depends_on:
      - build
    ports:
      - "8080:8080"


  volumes:
    mymavenbox:

