  version: "3"
  services:
    build:
      build: ./build
      volumes:
        - type: volume
          source: /home/ubuntu/
          target: /usr/local/build

    prod:
      build: ./prod
      volumes:
         - type: volume
           source: /home/ubuntu/
           target: /usr/local/tomcat/webapps
      depends_on:
         - build
      ports:
         - "8080:8080"

  volumes:
     /home/ubuntu/:

