  Version: '3'
  services:
    maven:
      build: sbor_dockerfile
    volumes:
      - type: volume
        source: mymavenbox
        target: /mymavenbox

    tomcat:
      build: prod_dockerfile
    volumes:
      - type: volume
        source: mytomcat
        target: /usr/local/tomcat
    ports:
      - "8080:8080"


  volumes:
    mymavenbox:
    mytomcat:

