  pipeline {
    agent {

        docker {
              image '178.154.206.16:8123/repository/dockerrepo/boxfuse01:latest'
              registryUrl 'http://178.154.206.16:8081/repository/dockerrepo/'
              registryCredentialsId '83fbad73-ab62-41a8-aa4b-090549afe37e'
              args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
         stage ('git') {
             steps {
                 git 'https://github.com/gandalff512/box_fuse_test01.git'
             }
         }
         stage ('build') {
             steps {
               sh 'mvn package'
             }
         }
         stage ('make docker') {
             steps {
                sh 'docker build -t prodimage .'
                sh 'docker tag prodimage 178.154.206.16:8123/repository/dockerrepo/prodimage:latest'
                sh 'docker push 178.154.206.16:8123/repository/dockerrepo/prodimage:latest'
             }
         }
         stage ('deploy') {
             steps {
                sh 'docker run -d  -p 8080:8080 178.154.206.16:8123/repository/dockerrepo/prodimage:latest'
             }
         }
     }
  }