  pipeline {
      agent {

          docker {
              image '178.154.206.16:8123/boxfuse01:latest'
              args '--privileged -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.m2:/root/.m2'
          }
      }

      stages {
           stage ('git') {
               steps {
                   git 'https://github.com/gandalff512/box_fuse_test01.git'
               }
           }
           stage ('build') {
               steps {
                 sh 'mvn package'
               }
           }
           stage ('make docker') {
               steps {
                  sh 'docker build -t prodimage .'
                  sh 'docker tag prodimage 178.154.206.16:8123/prodimage:latest'
                  sh 'docker push 178.154.206.16:8123/prodimage:latest'
               }
           }
           stage ('deploy') {
               steps {
                  sh 'docker run -d  -p 8080:8080 178.154.206.16:8123/prodimage:latest'
               }
           }
      }
  }