---
- name: Ensure tomcat is present
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"

- name: Copy .war prod machine
  copy:
    src: ./build/files/hello-1.0.war
    dest: "{{ tomcatdir }}"
  notify:
    - restart tomcat9
