  tasks:
  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     state: present
     update_cache: yes

  - name: Copy .war prod machine
    copy:
     src: /tmp/fetched/hello-1.0.war
     dest: /var/lib/tomcat9/webapps/hello-1.0.war
