---
- name: Ensure tomcat is present
  apt:
    name: tomcat9
    state: present
    update_cache: yes

- name: Copy .war prod machine
  copy:
    src: ./build/files/hello-1.0.war
    dest: "{{ tomcatdir }}"
  notify:
    - restart tomcat9
